[app]
name = "pymap"
version = "0.0.1"
description = "PyLens helps you find PyPI packages through natural language prompts"
environment = "prod"

[api]
host = "0.0.0.0"
port = 8080
debug = false
cors_origins = ["https://pymap.io"]
embeddings_model_name = "all-mpnet-base-v2"
weight_similarity = 0.0
weight_weekly_downloads = 1.0

[etl]
google_file_id = "1xX8gVnyfLJeDLSkb9ckGq_81kn-DK6om"
overwrite_download = false
frac_data_to_include = 1.0

[storage]
data_folder = "data"
# Always download from blob on API startup (prod reliability)
force_download_on_startup = true

[files]
raw_dataset_csv = "raw_dataset.csv"
processed_dataset_csv = "processed_dataset.csv"
dataset_for_api_csv = "dataset_for_api.csv"
embeddings_parquet = "embeddings.parquet"
